# Generated by Django 3.2.8 on 2021-12-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donate',
            name='accept',
            field=models.CharField(default='승인대기', max_length=10),
        ),
        migrations.AlterField(
            model_name='donate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
